version: 0.2

phases:
  install:
    commands:
      - yarn install
  pre_build:
    commands:
      - yarn graphql:generate twenty-front
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - yarn test twenty-front
      - yarn storybook:test twenty-front
artifacts:
  files:
    - '**/*'
  base-directory: 'build' # or the directory where your build artifacts are output

